server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/analysis-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false

services:
  storage:
    base-url: ${SERVICES_STORAGE_BASE_URL:http://localhost:8081}
